volumes:
    langgraph-data:
        driver: local
services:
    langgraph-api:
        image: evdev3/anubis-langgraph-api:latest
        ports:
            - "80:8000"
            - "5687:5687"
        healthcheck:
            test: python /api/healthcheck.py
            interval: 60s
            start_interval: 1s
            start_period: 10s
        env_file:
            - .env