volumes:
    langgraph-data:
        driver: local
services:
    langgraph-api:
        dns:
            - 168.83.129.16
            - 8.8.8.8
        ports:
            - "8123:8000"
            - "5678:5678"
        healthcheck:
            test: python /api/healthcheck.py
            interval: 60s
            start_interval: 1s
            start_period: 10s
        env_file:
            - .env
        volumes:
            - .:/deps/anubis
        build:
            context: .
            dockerfile: Dockerfile