volumes:
    langgraph-data:
        driver: local
    grafana-storage:
        driver: local
        
services:
    langgraph-api-prod:
        image: evdev3/anubis-langgraph-api:latest
        pull_policy: never
        dns:
            - 168.83.129.16
            - 8.8.8.8
        ports:
            - "8124:8000"
        extra_hosts:
            - "host.docker.internal:host-gateway" 
        healthcheck:
            test: python /api/healthcheck.py
            interval: 60s
            start_interval: 1s
            start_period: 10s
        env_file:
            - .env
        volumes:
            - .:/deps/anubis`
            - ~/.cache/huggingface:/root/.cache/huggingface

    grafana:
        image: grafana/grafana:latest
        ports:
            - "3000:3000"
        extra_hosts:
            - "host.docker.internal:host-gateway" 
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
            - grafana-storage:/var/lib/grafana
        restart: unless-stopped