apiVersion: 1

datasources:
  - name: MyPostgresData
    uid: MyPostgresData
    type: postgres
    access: proxy
    url: host.docker.internal:5432
    user: ${PG_USER}
    database: postgres
    secureJsonData:
      password: ${PG_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true