# src/anubis/utils/billing/__init__.py

"""Metering and subscription-tier billing for Neural Nexus.

This package is the single source of truth for the three subscription tiers
(free, pro, premium), the four separately-budgeted, per-user, monthly-resetting
usage meters, and the helpers that report usage to Stripe Billing Meters and
enforce per-tier capability and allotment gating.
"""

from src.anubis.utils.billing.config import (
    StripeBillingConfig,
    TierStripeIdentifiers,
    billing_config_source_conflict,
    current_stripe_billing_config,
    initialize_stripe_billing_config,
    load_stripe_billing_config,
    resolve_stripe_billing_config_json,
)
from src.anubis.utils.billing.estimation import (
    ESTIMATED_AUDIO_FALLBACK_DURATION_SECONDS,
    TokenEstimateBreakdown,
    TokenEstimationError,
    count_words,
    estimate_analysis_tokens,
    estimate_audio_diarization_tokens,
    estimate_audio_input_tokens,
    estimate_image_input_tokens,
    estimate_image_tokens,
    estimate_media_item_token_breakdown,
    estimate_media_item_tokens,
    estimate_message_request_token_breakdown,
    estimate_message_request_tokens,
    estimate_text_tokens_from_characters,
    estimate_text_tokens_from_words,
    estimated_transcript_tokens_for_duration,
)
from src.anubis.utils.billing.gating import (
    CanceledTierContext,
    SubscribeAction,
    TierChangePlan,
    TrialContext,
    canceled_tier_allotment_floor_applies,
    customer_has_payment_method,
    exhausted_allotment_block_reason,
    MeteringBypass,
    is_admin_metering_bypass,
    is_dev_metered_enforcement_bypass,
    parse_metering_bypass_identifiers,
    resolve_metering_bypass,
    is_anonymous_user,
    plan_resubscribe_usage_window,
    plan_subscribe_action,
    plan_tier_change,
    subscription_has_pending_downgrade_schedule,
    resolve_canceled_tier_context,
    resolve_effective_monthly_allotment,
    resolve_metering_user_id,
    resolve_pay_per_use_enabled,
    resolve_stripe_customer_id,
    resolve_tier,
    resolve_trial_context,
    resolve_usage_period_anchor,
    resolve_use_adapter_inference,
    user_has_capability,
)
from src.anubis.utils.billing.subscription_lifecycle import (
    LIVE_SUBSCRIPTION_STATUSES,
    clear_pending_cancellation,
    release_pending_subscription_schedule,
    resolve_checkout_trial_period_days,
    subscription_period_bounds,
)
from src.anubis.utils.billing.stripe_usage import (
    fetch_stripe_period_usage,
    invalidate_stripe_usage_cache,
    reconcile_period_usage,
    stripe_usage_source_of_truth_enabled,
)
from src.anubis.utils.billing.system_prompt_estimate_cache import (
    fetch_system_prompt_token_estimate,
    invalidate_system_prompt_token_estimate,
    record_system_prompt_token_estimate,
)
from src.anubis.utils.billing.tool_schema_estimate_cache import (
    estimate_tool_schema_tokens_for_tools,
    fetch_or_measure_deep_agent_tool_schema_token_estimate,
    invalidate_deep_agent_tool_schema_token_estimate,
    measure_deep_agent_tool_schema_token_estimate,
)
from src.anubis.utils.billing.metering import (
    billable_tokens_from_metadata,
    ensure_anonymous_billing_customers_table,
    ensure_api_metrics_table,
    fetch_anonymous_stripe_customer_id,
    fetch_rolling_window_usage,
    persist_anonymous_stripe_customer_id,
    fetch_usage_by_meter_since,
    fetch_usage_since,
    persist_api_metrics_row,
    report_adapter_training_usage,
    report_meter_event,
    resolve_usage_period_end,
    resolve_usage_period_start,
    token_rate_limit_retry_after_seconds,
)
from src.anubis.utils.billing.usage_notification import (
    schedule_usage_notification,
)
from src.anubis.utils.billing.tiers import (
    METER_EVENT_NAMES,
    TIER_DEFINITIONS,
    MeterAllotment,
    SubscriptionTier,
    TierCapability,
    TierDefinition,
    UsageMeter,
    tier_allotment_for_meter,
    tier_from_value,
    tier_has_capability,
)

__all__ = [
    "SubscriptionTier",
    "UsageMeter",
    "TierCapability",
    "TierDefinition",
    "MeterAllotment",
    "TIER_DEFINITIONS",
    "METER_EVENT_NAMES",
    "tier_from_value",
    "tier_has_capability",
    "tier_allotment_for_meter",
    "StripeBillingConfig",
    "TierStripeIdentifiers",
    "billing_config_source_conflict",
    "current_stripe_billing_config",
    "initialize_stripe_billing_config",
    "load_stripe_billing_config",
    "resolve_stripe_billing_config_json",
    "is_anonymous_user",
    "MeteringBypass",
    "is_admin_metering_bypass",
    "is_dev_metered_enforcement_bypass",
    "parse_metering_bypass_identifiers",
    "resolve_metering_bypass",
    "customer_has_payment_method",
    "exhausted_allotment_block_reason",
    "plan_subscribe_action",
    "plan_tier_change",
    "subscription_has_pending_downgrade_schedule",
    "canceled_tier_allotment_floor_applies",
    "plan_resubscribe_usage_window",
    "resolve_canceled_tier_context",
    "resolve_effective_monthly_allotment",
    "resolve_trial_context",
    "CanceledTierContext",
    "SubscribeAction",
    "TierChangePlan",
    "TrialContext",
    "resolve_metering_user_id",
    "resolve_pay_per_use_enabled",
    "resolve_stripe_customer_id",
    "resolve_tier",
    "resolve_usage_period_anchor",
    "resolve_use_adapter_inference",
    "user_has_capability",
    "LIVE_SUBSCRIPTION_STATUSES",
    "clear_pending_cancellation",
    "release_pending_subscription_schedule",
    "resolve_checkout_trial_period_days",
    "subscription_period_bounds",
    "fetch_stripe_period_usage",
    "invalidate_stripe_usage_cache",
    "reconcile_period_usage",
    "stripe_usage_source_of_truth_enabled",
    "report_meter_event",
    "schedule_usage_notification",
    "report_adapter_training_usage",
    "billable_tokens_from_metadata",
    "TokenEstimateBreakdown",
    "TokenEstimationError",
    "count_words",
    "estimate_analysis_tokens",
    "estimate_audio_diarization_tokens",
    "estimate_audio_input_tokens",
    "estimate_image_input_tokens",
    "estimate_image_tokens",
    "estimate_media_item_token_breakdown",
    "estimate_media_item_tokens",
    "estimate_message_request_token_breakdown",
    "estimate_message_request_tokens",
    "estimate_text_tokens_from_characters",
    "estimate_text_tokens_from_words",
    "estimated_transcript_tokens_for_duration",
    "ESTIMATED_AUDIO_FALLBACK_DURATION_SECONDS",
    "fetch_system_prompt_token_estimate",
    "invalidate_system_prompt_token_estimate",
    "record_system_prompt_token_estimate",
    "estimate_tool_schema_tokens_for_tools",
    "fetch_or_measure_deep_agent_tool_schema_token_estimate",
    "invalidate_deep_agent_tool_schema_token_estimate",
    "measure_deep_agent_tool_schema_token_estimate",
    "fetch_usage_since",
    "fetch_usage_by_meter_since",
    "fetch_rolling_window_usage",
    "resolve_usage_period_start",
    "resolve_usage_period_end",
    "token_rate_limit_retry_after_seconds",
    "ensure_api_metrics_table",
    "persist_api_metrics_row",
    "ensure_anonymous_billing_customers_table",
    "fetch_anonymous_stripe_customer_id",
    "persist_anonymous_stripe_customer_id",
]
