services:
  neural-nexus-api:
    build: .
    ports:
      - "8000:8000"
      - "5687:5687"
    environment:
      - PYDEVD_DISABLE_FILE_VALIDATION=1
    env_file:
      - .env.dev
    volumes:
      - .:/app
    command: python -m debugpy --listen 0.0.0.0:5687 -m uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload